#!/usr/bin/env bash
# Configure UFW firewall to block all incoming traffic except SSH, HTTP and HTTPS

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw enable
