#!/usr/bin/env bash
# Starts the Apache service inside the running Docker container and checks status

docker exec -i "$(docker ps -q)" service apache2 start
docker exec -i "$(docker ps -q)" service apache2 status
