#!/usr/bin/env bash
# Configure nginx to add a custom X-Served-By response header

apt-get update
apt-get install -y nginx

sed -i "/server {/a\\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx restart
