#!/usr/bin/env bash
# Install and configure HAProxy as a round-robin load balancer

apt-get update
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
        log /dev/log local0
        log /dev/log local1 notice
        daemon

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend web_front
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server web01 54.227.137.95:80 check
        server web02 13.221.90.222:80 check
EOF

service haproxy restart
