#!/usr/bin/env bash
# Configures Nginx on a new Ubuntu server with basic index page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx start
