#!/usr/bin/env bash
# Configures Nginx with a 301 redirection for /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

# Insert redirect rule right after server_name line in default config
sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

service nginx restart
