#!/usr/bin/env bash
# Installs and configures Nginx with a custom 404 page

apt-get update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a\
\
    error_page 404 /404.html;\
\
    location = /404.html {\
        internal;\
    }\
\
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

service nginx restart
